import React, { createContext, useContext, useState } from "react";

type Language = "EN" | "HI" | "TE" | "TA" | "MR";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (path: string) => string;
}

const translations: Record<Language, any> = {
  EN: {
    navbar: {
      home: "Home",
      departments: "Departments",
      doctors: "Doctors",
      services: "Services",
      contact: "Contact",
      book: "Book Appointment",
      tools: "Health Tools",
      queue: "Live Queue",
    },
    hero: {
      tag: "Best Medical Care",
      title: "Your Health is Our",
      titleAccent: "Top Priority",
      desc: "Experience world-class healthcare with our expert team and state-of-the-art facilities.",
      cta: "Book Appointment",
      view: "View Services",
    },
    common: {
      calculate: "Calculate",
      reset: "Reset",
      loading: "Loading...",
      success: "Success!",
      results: "Results",
      error: "Server unavailable",
      booking: "Booking appointment...",
      selectLanguage: "Select Language",
      close: "Close"
    },
    bmi: {
      title: "BMI Calculator",
      weight: "Weight (kg)",
      height: "Height (cm)",
      category: "Category",
      underweight: "Underweight",
      normal: "Normal",
      overweight: "Overweight",
      obese: "Obese",
    },
    footer: {
      rights: "All rights reserved.",
      quickLinks: "Quick Links",
      contactUs: "Contact Us",
    },
    phcLocator: {
      tag: "Rural Accessibility",
      title: "Find Your Nearest Government Center",
      desc: "We help you locate state-run Primary Health Centers (PHC) and civil hospitals in your vicinity for free or specialized medical care.",
      btn: "Get My Location",
      detecting: "Detecting Location...",
      emptyTitle: "Find Healthcare Centers",
      emptyDesc: "Click 'Get My Location' to automatically detect your position and show the nearest primary health centers on a zero-cost interactive map.",
      mapHeader: "Interactive Map",
      showing: "Showing nearby centers",
      youAreHere: "You are here",
      liveTracking: "Live Tracking Active",
      accuracy: "High Accuracy Mode",
      fallback: "Using default location",
      zeroCost: "Zero Cost Map",
    },
    healthVault: {
      tag: "Urban Smart Healthcare",
      title: "Your Digital Health Vault",
      desc: "Securely store and manage your medical prescriptions, lab reports, and imaging history. Access them anytime with bank-grade encryption. All uploads are automatically processed for data extraction.",
      uploadTitle: "Click or Drag Reports",
      uploadDesc: "Supports PDF, JPG, PNG (Max 5MB)",
      uploading: "Uploading Securely...",
      searchPlaceholder: "Search records...",
      recentRecords: "Recent Records",
      stored: "Stored",
      syncing: "Syncing",
      encrypted: "Encrypted",
      removed: "Record removed from view",
      uploadSuccess: "File uploaded successfully!",
      uploadError: "Upload failed. Check settings.",
      diabetes_report: "Diabetes Pathology Report",
      hypertension_report: "Hypertension & Cardiac Risk",
      kidney_report: "Chronic Kidney Disease Report",
      pathology: "Pathology",
      cardiology: "Cardiology",
      nephrology: "Nephrology",
      urbanSmart: "Urban Smart Healthcare",
      certifiedVault: "Hospital Certified Health Vault",
      vaultDesc: "Access your verified medical reports globally with dual-layer 256-bit encryption. All uploads are automatically processed for data extraction.",
      uploadLab: "Upload Laboratory Report",
      supportPdf: "Supports PDF • Max 10MB",
      cloudSync: "Cloud Sync Status",
      smartVaultName: "MediNova SmartVault",
      activeBadge: "ACTIVE",
      used: "Used",
      total: "Total",
      searchRepo: "Search your medical repository...",
      reportsCount: "Reports",
      verifiedReport: "Verified Report",
      certifiedBadge: "Certified",
      viewReport: "View Medical Report",
      downloadPdf: "Download Encrypted PDF",
      deletePerm: "Delete permanently",
      noRecords: "No Matching Records",
      trySearch: "Try searching for a different keyword or category.",
      modalDownload: "Download",
      secureView: "Secure View Active",
      smartLink: "MediNova SmartLink Technology • Multi-Region Encryption",
    },
    queue: {
      tag: "Live Hospital Traffic",
      title: "Real-Time",
      titleAccent: "Queue Intelligence",
      desc: "Check live OPD waiting times and patient traffic before you visit. Plan your consultation efficiently with our predictive queuing system.",
      notifyOn: "Notifications On",
      notifyMe: "Notify Me of Wait Changes",
      status: "Department Status",
      live: "LIVE",
      waiting: "Waiting Patients",
      avgWait: "Avg. Wait Time",
      serving: "NOW SERVING TOKEN",
      lastUpdated: "LAST UPDATED",
      justNow: "Just Now",
      schedulePrompt: "Want to schedule for a specific time instead?",
      bookPrivate: "Book Private Slot",
    },
    healthTools: {
      tag: "Health Precision",
      title: "Smart Health Tools",
      desc: "Quickly assess your key health metrics with our AI-powered calculators.",
      bmi: "BMI Calculator",
      weight: "Weight",
      height: "Height",
      category: "Category",
      underweight: "Underweight",
      normal: "Normal",
      overweight: "Overweight",
      obese: "Obese",
    },
    services: {
      tag: "Hospital Services",
      title: "Comprehensive Healthcare",
      desc: "Experience world-class medical services tailored to your needs with advanced technology and expert care.",
      ai: { 
        title: "AI Assistant", 
        desc: "24/7 AI-powered health guidance and instant support.",
        details: "Our 24/7 AI-powered health assistant provides instant answers to medical queries, helps triage symptoms using advanced algorithms, and offers personalized health tips based on your input. It's like having a doctor's guidance in your pocket at all times.",
        features: ["Symptom Triage", "Instant Medical Q&A", "Personalized Health Tips", "24/7 Availability"]
      },
      doctors: { 
        title: "Specialists", 
        desc: "Connect with top-rated medical professionals.",
        details: "Access a network of top-rated medical specialists across various fields including Cardiology, Neurology, and Oncology. Our platform simplifies the process of finding and connecting with the right expert for your specific health needs.",
        features: ["Expert Consultations", "Multi-Specialty Care", "Easy Connectivity", "Verified Professionals"]
      },
      checkup: { 
        title: "Health Checkups", 
        desc: "Comprehensive screening for early detection.",
        details: "Stay ahead of potential health issues with our comprehensive screening packages. From basic wellness exams to advanced diagnostic profiles, we offer tailored checkups for all ages to ensure early detection and prevention.",
        features: ["Full Body Screening", "Early Detection", "Tailored Packages", "Expert Analysis"]
      },
      mental: { 
        title: "Mental Health", 
        desc: "Professional counseling and support services.",
        details: "Prioritize your emotional well-being with our professional counseling services. We provide a safe, confidential environment for therapy sessions, stress management, and support for various mental health conditions.",
        features: ["Confidential Counseling", "Stress Management", "Therapy Sessions", "Emotional Support"]
      },
      lab: { 
        title: "Lab Services", 
        desc: "Advanced diagnostic and testing facilities.",
        details: "Experience precision diagnostics with our state-of-the-art laboratory facilities. We offer a wide range of tests with fast turnaround times, ensuring you get the accurate data needed for effective treatment planning.",
        features: ["Advanced Diagnostics", "Fast Results", "Wide Test Range", "Certified Labs"]
      },
      peds: { 
        title: "Pediatrics", 
        desc: "Specialized care for infants and children.",
        details: "Specialized, compassionate care for your little ones. Our pediatric department is designed to be child-friendly, offering everything from newborn care and vaccinations to specialized treatment for childhood illnesses.",
        features: ["Newborn Specialist", "Child-Friendly Environment", "Vaccinations", "Growth Monitoring"]
      },
      features: { 
        emergency: "Emergency", 
        monitoring: "Live Tracking", 
        scheduling: "Easy Booking" 
      },
      learnMore: "Learn More",
      officialService: "Official Hospital Service",
      getService: "Get This Service"
    },
    appointment: {
      consultExperts: "Consult with experts",
      title: "Schedule Your Medical Consultation",
      desc: "Take the first step towards better health. Fill out the form and our team will get back to you to confirm your appointment.",
      nameLabel: "Full Name",
      phoneLabel: "Phone Number",
      deptLabel: "Department",
      docLabel: "Doctor",
      dateLabel: "Date",
      timeLabel: "Time",
      msgLabel: "Message (Optional)",
      msgPlaceholder: "Tell us about your symptoms...",
      successDesc: "Your appointment has been booked successfully. Our team will contact you shortly.",
      thanks: "Great, Thanks!",
      confirmed: "Confirmed",
      status: "Status",
      nameReq: "Full name is required",
      phoneReq: "Phone number is required",
      phoneDigits: "Phone must be exactly 10 digits",
      deptReq: "Please select a department",
      docReq: "Please select a doctor",
      dateReq: "Date is required",
      datePast: "Date cannot be in the past",
      timeReq: "Time is required",
      selectDept: "Select Department",
      selectDoc: "Select Doctor",
      selectDeptFirst: "Select Dept First"
    },
    doctors: {
      tag: "Expert Team members",
      title: "Meet Our Dedicated Specialists",
      searchPlaceholder: "Search by name or specialty...",
      bookNow: "Book Now",
      noFound: "No Specialists Found",
      noFoundDesc: "Try searching for another name or specialty.",
      clearSearch: "Clear Search",
      exp: "EXP",
      rating: "Rating"
    },
    departments: {
      tag: "Medical Excellence",
      title: "Specialized Departments",
      desc: "Our world-class specialists provide expert care across various medical fields.",
      cardiology: { name: "Cardiology", desc: "Heart & Vascular Care" },
      neurology: { name: "Neurology", desc: "Brain & Nerve Care" },
      orthopedics: { name: "Orthopedics", desc: "Bone & Joint Care" },
      emergency: { name: "Emergency Med", desc: "24/7 Critical Care" },
      pediatrics: { name: "Pediatrics", desc: "Child Healthcare" },
      oncology: { name: "Oncology", desc: "Cancer Treatment" },
      "general-medicine": { name: "General Medicine", desc: "Preventive Care" }
    },
    specialties: {
      "Chief Cardiologist": "Chief Cardiologist",
      "Neurology Specialist": "Neurology Specialist",
      "Pediatric Surgeon": "Pediatric Surgeon",
      "Orthopedic Expert": "Orthopedic Expert",
      "General Physician": "General Physician",
      "Emergency Medicine Specialist": "Emergency Medicine Specialist"
    },
    chat: {
      welcome: "👋 Hello! I'm NovaBot. How can we help you today?",
      placeholder: "Ask me anything about your health...",
      typing: "NovaBot is typing...",
      disclaimer: "⚠️ This AI assistant is for informational purposes only. Consult a doctor for medical diagnosis.",
      error: "Something went wrong. Please try again.",
      quickHelp: "Quick Help",
      send: "Send"
    },
    symptoms: {
      fever: "Fever",
      cough: "Cough",
      headache: "Headache",
      fatigue: "Fatigue",
      chest_pain: "Chest Pain",
      breath: "Shortness of Breath",
      vomiting: "Vomiting",
      dizziness: "Dizziness"
    }
  },
  HI: {
    navbar: {
      home: "होम",
      departments: "विभाग",
      doctors: "डॉक्टर",
      services: "सेवाएं",
      contact: "संपर्क",
      book: "अपॉइंटमेंट बुक करें",
      tools: "स्वास्थ्य उपकरण",
      queue: "लाइव कतार",
    },
    hero: {
      tag: "सर्वश्रेष्ठ चिकित्सा देखभाल",
      title: "आपका स्वास्थ्य हमारी",
      titleAccent: "शीर्ष प्राथमिकता है",
      desc: "हमारी विशेषज्ञ टीम और अत्याधुनिक सुविधाओं के साथ विश्व स्तरीय स्वास्थ्य सेवा का अनुभव करें।",
      cta: "अपॉइंटमेंट बुक करें",
      view: "सेवाएं देखें",
    },
    common: {
      calculate: "गणना करें",
      reset: "रीसेट करें",
      loading: "लोड हो रहा है...",
      success: "सफलता!",
      results: "परिणाम",
      error: "सर्वर उपलब्ध नहीं है",
      booking: "अपॉइंटमेंट बुक हो रहा है...",
      selectLanguage: "भाषा चुनें",
      close: "बंद करें"
    },
    bmi: {
      title: "बीएमआई कैलकुलेटर",
      weight: "वजन (किलो)",
      height: "ऊंचाई (सेमी)",
      category: "श्रेणी",
      underweight: "अंडरवेट",
      normal: "सामान्य",
      overweight: "ओवरवेट",
      obese: "मोटापे से ग्रस्त",
    },
    footer: {
      rights: "सर्वाधिकार सुरक्षित।",
      quickLinks: "त्वरित लिंक",
      contactUs: "संपर्क करें",
    },
    phcLocator: {
      tag: "ग्रामीण पहुंच",
      title: "अपने निकटतम सरकारी केंद्र का पता लगाएं",
      desc: "हम आपको मुफ्त या विशेष चिकित्सा देखभाल के लिए अपने आसपास के सरकारी प्राथमिक स्वास्थ्य केंद्रों (PHC) और नागरिक अस्पतालों का पता लगाने में मदद करते हैं।",
      btn: "मेरा स्थान प्राप्त करें",
      detecting: "स्थान का पता लगाया जा रहा है...",
      emptyTitle: "स्वास्थ्य देखभाल केंद्रों को खोजें",
      emptyDesc: "'मेरा स्थान प्राप्त करें' पर क्लिक करें ताकि स्वचालित रूप से आपकी स्थिति का पता लगाया जा सके और इंटरैक्टिव मानचित्र पर निकटतम सरकारी स्वास्थ्य केंद्रों को दिखाया जा सके।",
      mapHeader: "इंटरैक्टिव मानचित्र",
      showing: "पास के केंद्रों को दिखाया जा रहा है",
      youAreHere: "आप यहाँ हैं",
      liveTracking: "लाइव ट्रैकिंग सक्रिय है",
      accuracy: "उच्च सटीकता मोड",
      fallback: "डिफ़ॉल्ट स्थान का उपयोग किया जा रहा है",
      zeroCost: "शून्य लागत मानचित्र",
    },
    healthVault: {
      tag: "शहरी स्मार्ट स्वास्थ्य सेवा",
      title: "आपका डिजिटल हेल्थ वॉल्ट",
      desc: "बैंक-स्तरीय एन्क्रिप्शन के साथ अपने चिकित्सा नुस्खे, लैब रिपोर्ट और इमेजिंग इतिहास को सुरक्षित रूप से संग्रहीत और प्रबंधित करें। सभी अपलोड स्वचालित रूप से डेटा निष्कर्षण के लिए संसाधित किए जाते हैं।",
      uploadTitle: "रिपोर्ट पर क्लिक करें या खींचें",
      uploadDesc: "PDF, JPG, PNG (अधिकतम 5MB) का समर्थन करता है",
      uploading: "सुरक्षित रूप से अपलोड हो रहा है...",
      searchPlaceholder: "रिकॉर्ड खोजें...",
      recentRecords: "हाल के रिकॉर्ड",
      stored: "संग्रहीत",
      syncing: "सिंक हो रहा है",
      encrypted: "एन्क्रिप्टेड",
      removed: "रिकॉर्ड हटा दिया गया",
      uploadSuccess: "फ़ाइल सफलतापूर्वक अपलोड हो गई!",
      uploadError: "अपलोड विफल रहा। सेटिंग्स जांचें।",
      diabetes_report: "मधुमेह पैथोलॉजी रिपोर्ट",
      hypertension_report: "उच्च रक्तचाप और हृदय जोखिम",
      kidney_report: "क्रोनिक किडनी रोग रिपोर्ट",
      pathology: "पैथोलॉजी",
      cardiology: "हृदयरोग विज्ञान",
      nephrology: "नेफ्रोलॉजी",
      urbanSmart: "शहरी स्मार्ट स्वास्थ्य सेवा",
      certifiedVault: "अस्पताल प्रमाणित हेल्थ वॉल्ट",
      vaultDesc: "डुअल-लेयर 256-बिट एन्क्रिप्शन के साथ विश्व स्तर पर अपनी सत्यापित चिकित्सा रिपोर्ट एक्सेस करें। सभी अपलोड स्वचालित रूप से डेटा निष्कर्षण के लिए संसाधित किए जाते हैं।",
      uploadLab: "प्रयोगशाला रिपोर्ट अपलोड करें",
      supportPdf: "PDF का समर्थन करता है • अधिकतम 10MB",
      cloudSync: "क्लाउड सिंक स्थिति",
      smartVaultName: "MediNova स्मार्टवॉल्ट",
      activeBadge: "सक्रिय",
      used: "उपयोग किया गया",
      total: "कुल",
      searchRepo: "अपनी चिकित्सा रिपॉजिटरी खोजें...",
      reportsCount: "रिपोर्ट",
      verifiedReport: "सत्यापित रिपोर्ट",
      certifiedBadge: "प्रमाणित",
      viewReport: "चिकित्सा रिपोर्ट देखें",
      downloadPdf: "एन्क्रिप्टेड PDF डाउनलोड करें",
      deletePerm: "स्थायी रूप से हटाएं",
      noRecords: "कोई मिलान रिकॉर्ड नहीं",
      trySearch: "एक अलग कीवर्ड या श्रेणी खोजने का प्रयास करें।",
      modalDownload: "डाउनलोड",
      secureView: "सुरक्षित दृश्य सक्रिय",
      smartLink: "MediNova स्मार्टलिंक तकनीक • बहु-क्षेत्रीय एन्क्रिप्शन",
    },
    queue: {
      tag: "लाइव अस्पताल ट्रैफिक",
      title: "वास्तविक समय",
      titleAccent: "कतार बुद्धिमत्ता",
      desc: "यात्रा करने से पहले लाइव ओपीडी प्रतीक्षा समय और रोगी भीड़ की जांच करें। हमारे पूर्वानुमानित कतार प्रणाली के साथ कुशलतापूर्वक अपने परामर्श की योजना बनाएं।",
      notifyOn: "सूचनाएं चालू",
      notifyMe: "प्रतीक्षा परिवर्तनों की सूचना दें",
      status: "विभाग की स्थिति",
      live: "लाइव",
      waiting: "प्रतीक्षारत रोगी",
      avgWait: "औसत प्रतीक्षा समय",
      serving: "अब टोकन परोस रहे हैं",
      lastUpdated: "अंतिम अपडेट",
      justNow: "अभी-अभी",
      schedulePrompt: "क्या इसके बजाय किसी विशिष्ट समय के लिए शेड्यूल करना चाहते हैं?",
      bookPrivate: "निजी स्लॉट बुक करें",
    },
    healthTools: {
      tag: "स्वास्थ्य परिशुद्धता",
      title: "स्मार्ट स्वास्थ्य उपकरण",
      desc: "हमारे एआई-पावर्ड कैलकुलेटर के साथ अपने प्रमुख स्वास्थ्य मैट्रिक्स का तुरंत आकलन करें।",
      bmi: "बीएमआई कैलकुलेटर",
      weight: "वजन",
      height: "ऊंचाई",
      category: "श्रेणी",
      underweight: "कम वजन",
      normal: "सामान्य",
      overweight: "अधिक वजन",
      obese: "मोटापा",
    },
    services: {
      tag: "अस्पताल सेवाएं",
      title: "व्यापक स्वास्थ्य देखभाल",
      desc: "उन्नत तकनीक और विशेषज्ञ देखभाल के साथ आपकी आवश्यकताओं के अनुरूप विश्व स्तरीय चिकित्सा सेवाओं का अनुभव करें।",
      ai: { 
        title: "AI सहायक", 
        desc: "24/7 AI-संचालित स्वास्थ्य मार्गदर्शन।",
        details: "हमारा 24/7 AI-संचालित स्वास्थ्य सहायक चिकित्सा प्रश्नों के त्वरित उत्तर प्रदान करता है, उन्नत एल्गोरिदम का उपयोग करके लक्षणों को प्राथमिकता देने में मदद करता है, और आपके इनपुट के आधार पर व्यक्तिगत स्वास्थ्य सुझाव देता है।",
        features: ["लक्षण छँटाई", "त्वरित चिकित्सा प्रश्नोत्तरी", "व्यक्तिगत स्वास्थ्य सुझाव", "24/7 उपलब्धता"]
      },
      doctors: { 
        title: "विशेषज्ञ", 
        desc: "शीर्ष रेटेड चिकित्सा पेशेवरों से जुड़ें।",
        details: "विभिन्न क्षेत्रों में शीर्ष रेटेड चिकित्सा विशेषज्ञों के नेटवर्क तक पहुँचें। हमारा प्लेटफ़ॉर्म आपकी विशिष्ट स्वास्थ्य आवश्यकताओं के लिए सही विशेषज्ञ को खोजने और उनसे जुड़ने की प्रक्रिया को सरल बनाता है।",
        features: ["विशेषज्ञ परामर्श", "बहु-विशिष्ट देखभाल", "आसान कनेक्टिविटी", "सत्यापित पेशेवर"]
      },
      checkup: { 
        title: "स्वास्थ्य जांच", 
        desc: "जल्दी पता लगाने के लिए व्यापक जांच।",
        details: "हमारे व्यापक स्क्रीनिंग पैकेज के साथ संभावित स्वास्थ्य मुद्दों से आगे रहें। हम शीघ्र पता लगाने और रोकथाम सुनिश्चित करने के लिए सभी उम्र के लोगों के लिए विशेष जांच प्रदान करते हैं।",
        features: ["पूरे शरीर की स्क्रीनिंग", "प्रारंभिक पहचान", "अनुकूलित पैकेज", "विशेषज्ञ विश्लेषण"]
      },
      mental: { 
        title: "मानसिक स्वास्थ्य", 
        desc: "पेशेवर परामर्श और सहायता सेवाएँ।",
        details: "हमारी पेशेवर परामर्श सेवाओं के साथ अपने भावनात्मक कल्याण को प्राथमिकता दें। हम चिकित्सा सत्रों और तनाव प्रबंधन के लिए एक सुरक्षित, गोपनीय वातावरण प्रदान करते हैं।",
        features: ["गोपनीय परामर्श", "तनाव प्रबंधन", "चिकित्सा सत्र", "भावनात्मक समर्थन"]
      },
      lab: { 
        title: "लैब सेवाएं", 
        desc: "उन्नत नैदानिक परीक्षण सुविधाएं।",
        details: "हमारी अत्याधुनिक प्रयोगशाला सुविधाओं के साथ सटीक निदान का अनुभव करें। हम तेजी से परिणाम प्रदान करते हैं, यह सुनिश्चित करते हुए कि आपको प्रभावी उपचार योजना के लिए सटीक डेटा मिले।",
        features: ["उन्नत नैदानिक", "तेजी से परिणाम", "व्यापक परीक्षण रेंज", "प्रमाणित लैब"]
      },
      peds: { 
        title: "बाल रोग", 
        desc: "शिशुओं और बच्चों के लिए विशेष देखभाल।",
        details: "नन्हे-मुन्नों के लिए विशेष देखभाल। हमारा बाल रोग विभाग बच्चों के अनुकूल बनाया गया है, जो टीकाकरण से लेकर बचपन की बीमारियों के उपचार तक सब कुछ प्रदान करता है।",
        features: ["नवजात विशेषज्ञ", "बच्चों के अनुकूल माहौल", "टीकाकरण", "विकास की निगरानी"]
      },
      features: { 
        emergency: "आपातकालीन", 
        monitoring: "लाइव ट्रैकिंग", 
        scheduling: "आसान बुकिंग" 
      },
      learnMore: "अधिक जानें",
      officialService: "आधिकारिक अस्पताल सेवा",
      getService: "यह सेवा प्राप्त करें"
    },
    appointment: {
      consultExperts: "विशेषज्ञों से सलाह लें",
      title: "अपना मेडिकल परामर्श निर्धारित करें",
      desc: "बेहतर स्वास्थ्य की ओर पहला कदम उठाएं। फॉर्म भरें और हमारी टीम आपकी नियुक्ति की पुष्टि करने के लिए आपसे संपर्क करेगी।",
      nameLabel: "पूरा नाम",
      phoneLabel: "फोन नंबर",
      deptLabel: "विभाग",
      docLabel: "डॉक्टर",
      dateLabel: "तारीख",
      timeLabel: "समय",
      msgLabel: "संदेश (वैकल्पिक)",
      msgPlaceholder: "हमें अपने लक्षणों के बारे में बताएं...",
      successDesc: "आपकी नियुक्ति सफलतापूर्वक बुक हो गई है। हमारी टीम जल्द ही आपसे संपर्क करेगी।",
      thanks: "बहुत अच्छा, धन्यवाद!",
      confirmed: "पुख्ता",
      status: "स्थिति",
      nameReq: "पूरा नाम आवश्यक है",
      phoneReq: "फोन नंबर आवश्यक है",
      phoneDigits: "फोन बिल्कुल 10 अंकों का होना चाहिए",
      deptReq: "कृपया एक विभाग चुनें",
      docReq: "कृपया एक डॉक्टर चुनें",
      dateReq: "तारीख आवश्यक है",
      datePast: "तारीख अतीत में नहीं हो सकती",
      timeReq: "समय आवश्यक है",
      selectDept: "विभाग चुनें",
      selectDoc: "डॉक्टर चुनें",
      selectDeptFirst: "पहले विभाग चुनें"
    },
    doctors: {
      tag: "विशेषज्ञ टीम के सदस्य",
      title: "हमारे समर्पित विशेषज्ञों से मिलें",
      searchPlaceholder: "नाम या विशेषता के आधार पर खोजें...",
      bookNow: "अभी बुक करें",
      noFound: "कोई विशेषज्ञ नहीं मिला",
      noFoundDesc: "किसी अन्य नाम या विशेषता खोजने का प्रयास करें।",
      clearSearch: "खोज साफ करें",
      exp: "अनुभव",
      rating: "रेटिंग"
    },
    departments: {
      tag: "चिकित्सा उत्कृष्टता",
      title: "विशेषज्ञ विभाग",
      desc: "हमारे विश्व स्तरीय विशेषज्ञ विभिन्न चिकित्सा क्षेत्रों में विशेषज्ञ देखभाल प्रदान करते हैं।",
      cardiology: { name: "हृदय रोग विज्ञान", desc: "हृदय और नाड़ी की देखभाल" },
      neurology: { name: "तंत्रिका विज्ञान", desc: "मस्तिष्क और तंत्रिका देखभाल" },
      orthopedics: { name: "हड्डियों का रोग", desc: "हड्डी और जोड़ों की देखभाल" },
      emergency: { name: "आपातकालीन चिकित्सा", desc: "24/7 गंभीर देखभाल" },
      pediatrics: { name: "बाल रोग", desc: "बाल स्वास्थ्य सेवा" },
      oncology: { name: "कैंसर विज्ञान", desc: "कैंसर का उपचार" },
      "general-medicine": { name: "सामान्य औषध", desc: "निवारक देखभाल" }
    },
    specialties: {
      "Chief Cardiologist": "मुख्य हृदय रोग विशेषज्ञ",
      "Neurology Specialist": "न्यूरोलॉजी विशेषज्ञ",
      "Pediatric Surgeon": "बाल रोग सर्जन",
      "Orthopedic Expert": "हड्डी रोग विशेषज्ञ",
      "General Physician": "सामान्य चिकित्सक",
      "Emergency Medicine Specialist": "आपातकालीन चिकित्सा विशेषज्ञ"
    },
    chat: {
      welcome: "👋 नमस्ते! मैं नोवाबॉट (NovaBot) हूँ। आज हम आपकी क्या मदद कर सकते हैं?",
      placeholder: "अपने स्वास्थ्य के बारे में कुछ भी पूछें...",
      typing: "नोवाबॉट टाइप कर रहा है...",
      disclaimer: "⚠️ यह एआई सहायक केवल सूचनात्मक उद्देश्यों के लिए है।",
      error: "कुछ गलत हो गया। कृपया पुन: प्रयास करें।",
      quickHelp: "त्वरित सहायता",
      send: "भेजें"
    },
    symptoms: {
      fever: "बुखार",
      cough: "खांसी",
      headache: "सिरदर्द",
      fatigue: "थकान",
      chest_pain: "सीने में दर्द",
      breath: "सांस लेने में कठिनाई",
      vomiting: "उल्टी",
      dizziness: "चक्कर आना"
    }
  },
  TE: {
    navbar: {
      home: "హోమ్",
      departments: "విభాగాలు",
      doctors: "వైద్యులు",
      services: "సేవలు",
      contact: "సంప్రదించండి",
      book: "అపాయింట్మెంట్ బుక్ చేయండి",
      tools: "ఆరోగ్య సాధనాలు",
      queue: "లైవ్ క్యూ",
    },
    hero: {
      tag: "ఉత్తమ వైద్య సంరక్షణ",
      title: "మీ ఆరోగ్యం మా",
      titleAccent: "అత్యున్నత ప్రాధాన్యత",
      desc: "మా నిపుణుల బృందం మరియు అత్యాధునిక సౌకర్యాలతో ప్రపంచ స్థాయి ఆరోగ్య సంరక్షణను అనుభవించండి.",
      cta: "అపాయింట్మెంట్ బుక్ చేయండి",
      view: "సేవలను చూడండి",
    },
    common: {
      calculate: "లెక్కించు",
      reset: "రీసెట్ చేయండి",
      loading: "లోడ్ అవుతోంది...",
      success: "విజయం!",
      results: "ఫలితాలు",
      error: "సర్వర్ అందుబాటులో లేదు",
      booking: "అపాయింట్మెంట్ బుక్ చేయబడుతోంది...",
      selectLanguage: "భాషను ఎంచుకోండి",
      close: "మూసివేయి"
    },
    bmi: {
      title: "BMI కాలిక్యులేటర్",
      weight: "బరువు (కేజీలు)",
      height: "ఎత్తు (సెం.మీ.)",
      category: "వర్గం",
      underweight: "తక్కువ బరువు",
      normal: "సాధారణం",
      overweight: "అధిక బరువు",
      obese: "స్థూలకాయం",
    },
    footer: {
      rights: "సర్వ హక్కులు ప్రత్యేకించబడినవి.",
      quickLinks: "త్వరిత లింక్లు",
      contactUs: "మమ్మల్ని సంప్రదించండి",
    },
    phcLocator: {
      tag: "గ్రామీణ ప్రాప్యత",
      title: "మీకు దగ్గరలోని ప్రభుత్వ కేంద్రాన్ని కనుగొనండి",
      desc: "ఉచిత లేదా ప్రత్యేక వైద్య సంరక్షణ కోసం మీ ప్రాంతంలోని ప్రభుత్వ ప్రాథమిక ఆరోగ్య కేంద్రాలు (PHC) మరియు సివిల్ ఆసుపత్రులను కనుగొనడంలో మేము మీకు సహాయం చేస్తాము.",
      btn: "నా లొకేషన్ స్థితిని పొందండి",
      detecting: "లొకేషన్ గుర్తించబడుతోంది...",
      emptyTitle: "ఆరోగ్య సంరక్షణ కేంద్రాలను కనుగొనండి",
      emptyDesc: "మీ లొకేషన్ స్థితిని గుర్తించడానికి మరియు మ్యాప్‌లో సమీపంలోని ప్రభుత్వ ఆరోగ్య కేంద్రాలను చూడటానికి 'నా లొకేషన్ పొందండి' పై క్లిక్ చేయండి.",
      mapHeader: "ఇంటరాక్టివ్ మ్యాప్",
      showing: "సమీపంలోని కేంద్రాలను చూపుతోంది",
      youAreHere: "మీరు ఇక్కడ ఉన్నారు",
      liveTracking: "లైవ్ ట్రాకింగ్ యాక్టివ్",
      accuracy: "హై అక్యూరసీ మోడ్",
      fallback: "డిఫాల్ట్ లొకేషన్ ఉపయోగిస్తోంది",
      zeroCost: "ఉచిత మ్యాప్",
    },
    healthVault: {
      tag: "అర్బన్ స్మార్ట్ హెల్త్‌కేర్",
      title: "మీ డిజిటల్ హెల్త్ వాల్ట్",
      desc: "మీ వైద్య ప్రిస్క్రిప్షన్లు, ల్యాబ్ నివేదికలను బ్యాంక్-గ్రేడ్ ఎన్క్రిప్షన్ ద్వారా సురక్షితంగా నిల్వ చేయండి.",
      uploadTitle: "క్లిక్ చేయండి లేదా రిపోర్టులను డ్రాగ్ చేయండి",
      uploadDesc: "PDF, JPG, PNG (గరిష్టంగా 5MB) సపోర్ట్ చేస్తుంది",
      uploading: "సురక్షితంగా అప్‌లోడ్ చేయబడుతోంది...",
      searchPlaceholder: "రికార్డులను వెతకండి...",
      recentRecords: "ఇటీవలి రికార్డులు",
      stored: "సాధారణం",
      syncing: "సింక్ అవుతోంది",
      encrypted: "ఎన్క్రిప్టెడ్",
      removed: "రికార్డ్ తొలగించబడింది",
      uploadSuccess: "ఫైల్ విజయవంతంగా అప్‌లోడ్ చేయబడింది!",
      uploadError: "అప్‌లోడ్ ವಿಫಲమైంది. సెట్టింగ్‌లు తనిఖీ చేయండి.",
    },
    healthTools: {
      tag: "ఆరోగ్య ఖచ్చితత్వం",
      title: "స్మార్ట్ హెల్త్ టూల్స్",
      desc: "మా AI-ఆధారిత కాలిక్యులేటర్లతో మీ ఆరోగ్య ప్రమాణాలను త్వరగా అంచనా వేయండి.",
      bmi: "BMI కాలిక్యులేటర్",
      weight: "బరువు",
      height: "ఎత్తు",
      category: "వర్గం",
      underweight: "తక్కువ బరువు",
      normal: "సాధారణం",
      overweight: "అధిక బరువు",
      obese: "స్థూలకాయం",
    },
    services: {
      tag: "ఆసుపత్రి సేవలు",
      title: "సమగ్ర ఆరోగ్య సంరక్షణ",
      desc: "అధునాతన సాంకేతికత మరియు నిపుణుల సంరక్షణతో మీ అవసరాలకు తగిన ప్రపంచ స్థాయి వైద్య సేవలను అనుభవించండి.",
      ai: { 
        title: "AI అసిస్టెంట్", 
        desc: "24/7 AI-ఆధారిత ఆరోగ్య మార్గదర్శకత్వం.",
        details: "మా 24/7 AI-ఆధారిత ఆరోగ్య సహాయకుడు వైద్య ప్రశ్నలకు తక్షణ సమాధానాలను అందిస్తారు, నిపుణులైన అల్గారిథమ్‌లను ఉపయోగించి లక్షణాలను అంచనా వేయడానికి సహాయం చేస్తారు.",
        features: ["లక్షణాల అంచనా", "తక్షణ వైద్య ప్రశ్నలు", "వ్యక్తిగత ఆరోగ్య సూచనలు", "24/7 అందుబాటు"]
      },
      doctors: { 
        title: "నిపుణులు", 
        desc: "టాప్ రేటెడ్ వైద్య నిపుణులతో కనెక్ట్ అవ్వండి.",
        details: "కార్డియాలజీ, న్యూరాలజీ మరియు ఆంకాలజీ వంటి వివిధ రంగాలలోని అగ్రశ్రేణి వైద్య నిపుణుల నెట్‌వర్క్‌ను యాక్సెస్ చేయండి. మీ ఆరోగ్య అవసరాల కోసం సరైన నిపుణులను కనుగొనడం ఇప్పుడు సులభం.",
        features: ["నిపుణుల సంప్రదింపులు", "మల్టీ-స్పెషాలిటీ కేర్", "సులభమైన కనెక్టివిటీ", "ధృవీకరించబడిన నిపుణులు"]
      },
      checkup: { 
        title: "ఆరోగ్య పరీక్షలు", 
        desc: "ముందస్తు గుర్తింపు కోసం సమగ్ర స్క్రీనింగ్.",
        details: "మా సమగ్ర స్క్రీనింగ్ ప్యాకేజీలతో సంభావ్య ఆరోగ్య సమస్యల కంటే ముందే ఉండండి. వ్యాధులను ముందుగానే గుర్తించడానికి మరియు నివారించడానికి మేము అన్ని వయసుల వారికి తగిన పరీక్షలను అందిస్తాము.",
        features: ["పూర్తి బాడీ స్క్రీనింగ్", "ముందస్తు గుర్తింపు", "తగిన ప్యాకేజీలు", "నిపుణుల విశ్లేషణ"]
      },
      mental: { 
        title: "మానసిక ఆరోగ్యం", 
        desc: "వృత్తిపరమైన కౌన్సెలింగ్ మరియు మద్దతు.",
        details: "మా వృత్తిపరమైన కౌన్సెలింగ్ సేవలతో మీ మానసిక ఆరోగ్యాన్ని మెరుగుపరుచుకోండి. మేము థెరపీ సెషన్లు మరియు ఒత్తిడి నిర్వహణ కోసం సురక్షితమైన మరియు రహస్య వాతావరణాన్ని అందిస్తాము.",
        features: ["రహస్య కౌన్సెలింగ్", "ఒత్తిడి నిర్వహణ", "థెరపీ సెషన్లు", "మానసిక మద్దతు"]
      },
      lab: { 
        title: "ల్యాబ్ సేవలు", 
        desc: "అధునాతన రోగనిర్ధారణ పరీక్షా సౌకర్యాలు.",
        details: "మా అత్యాధునిక ప్రయోగశాల సౌకర్యాలతో ఖచ్చితమైన నిర్ధారణను అనుభవించండి. మేము వేగవంతమైన ఫలితాలను అందిస్తాము, తద్వారా మీరు సమర్థవంతమైన చికిత్స ప్రణాళికను పొందగలరు.",
        features: ["అధునాతన నిర్ధారణ", "వేగవంతమైన ఫలితాలు", "విస్తృత పరీక్షల శ్రేణి", "సర్టిఫైడ్ ల్యాబ్స్"]
      },
      peds: { 
        title: "పిల్లల వైద్యం", 
        desc: "శిశువులు మరియు పిల్లల కోసం ప్రత్యేక సంరక్షణ.",
        details: "మీ పిల్లల కోసం ప్రత్యేకమైన మరియు ప్రేమపూర్వకమైన సంరక్షణ. మా పీడియాట్రిక్ విభాగం పిల్లలకు అనుకూలంగా ఉంటుంది, టీకాల నుండి బాల్య అనారోగ్యాల చికిత్స వరకు ప్రతిదీ అందిస్తుంది.",
        features: ["నవజాత శిశు నిపుణులు", "పిల్లలకు అనుకూల వాతావరణం", "టీకాలు", "పెరుగుదల పర్యవేక్షణ"]
      },
      features: { 
        emergency: "అత్యవసర", 
        monitoring: "లైవ్ ట్రాకింగ్", 
        scheduling: "ఈజీ బుకింగ్" 
      },
      learnMore: "మరింత తెలుసుకోండి",
      officialService: "అధికారిక ఆసుపత్రి సేవ",
      getService: "ఈ సేవను పొందండి"
    },
    appointment: {
      consultExperts: "నిపుణులతో సంప్రదించండి",
      title: "మీ వైద్య సంప్రదింపులను షెడ్యూల్ చేయండి",
      desc: "మెరుగైన ఆరోగ్యం వైపు మొదటి అడుగు వేయండి. ఫారమ్‌ను నింపండి మరియు మీ నియామకాన్ని ధృవీకరించడానికి మా బృందం మిమ్మల్ని సంప్రదిస్తుంది.",
      nameLabel: "పూర్తి పేరు",
      phoneLabel: "ఫోన్ నంబర్",
      deptLabel: "విభాగం",
      docLabel: "డాక్టర్",
      dateLabel: "తేదీ",
      timeLabel: "సమయం",
      msgLabel: "సందేశం (ఐచ్ఛికం)",
      msgPlaceholder: "మీ లక్షణాల గురించి మాకు చెప్పండి...",
      successDesc: "మీ అపాయింట్‌మెంట్ విజయవంతంగా బుక్ చేయబడింది. మా బృందం త్వరలో మిమ్మల్ని సంప్రదిస్తుంది.",
      thanks: "సరే, ధన్యవాదాలు!",
      confirmed: "ధృవీకరించబడింది",
      status: "స్థితి",
      nameReq: "పూర్తి పేరు తప్పనిసరి",
      phoneReq: "ఫోన్ నంబర్ తప్పనిసరి",
      phoneDigits: "ఫోన్ ఖచ్చితంగా 10 అంకెలు ఉండాలి",
      deptReq: "దయచేసి ఒక విభాగాన్ని ఎంచుకోండి",
      docReq: "దయచేసి ఒక వైద్యుడిని ఎంచుకోండి",
      dateReq: "తేదీ తప్పనిసరి",
      datePast: "తేదీ గతంలో ఉండకూడదు",
      timeReq: "సమయం తప్పనిసరి",
      selectDept: "విభాగాన్ని ఎంచుకోండి",
      selectDoc: "డాక్టర్‌ని ఎంచుకోండి",
      selectDeptFirst: "ముందుగా విభాగాన్ని ఎంచుకోండి"
    },
    doctors: {
      tag: "నిపుణుల బృందం సభ్యులు",
      title: "మా అంకితభావం గల నిపుణులను కలవండి",
      searchPlaceholder: "పేరు లేదా స్పెషాలిటీ ద్వారా వెతకండి...",
      bookNow: "ఇప్పుడే బుక్ చేయండి",
      noFound: "నిపుణులు కనిపించలేదు",
      noFoundDesc: "మరో పేరు లేదా స్పెషాలిటీతో వెతకండి.",
      clearSearch: "సెర్చ్ క్లియర్ చేయండి",
      exp: "అనుభవం",
      rating: "రేటింగ్"
    },
    departments: {
      tag: "వైద్య శ్రేష్టత",
      title: "ప్రత్యేక విభాగాలు",
      desc: "మా ప్రపంచ స్థాయి నిపుణులు వివిధ వైద్య రంగాలలో నిపుణుల సంరక్షణను అందిస్తారు.",
      cardiology: { name: "కార్డియాలజీ", desc: "గుండె సంరక్షణ" },
      neurology: { name: "న్యూరాలజీ", desc: "మెదడు సంరక్షణ" },
      orthopedics: { name: "ఆర్తోపెడిక్స్", desc: "ఎముకల సంరక్షణ" },
      emergency: { name: "ఎమర్జెన్సీ మెడిసిన్", desc: "24/7 సంరక్షణ" },
      pediatrics: { name: "పీడియాట్రిక్స్", desc: "పిల్లల సంరక్షణ" },
      oncology: { name: "ఆంకాలజీ", desc: "క్యాన్సర్ చికిత్స" },
      "general-medicine": { name: "జనరల్ మెడిసిన్", desc: "నివారణ సంరక్షణ" }
    },
    specialties: {
      "Chief Cardiologist": "చీఫ్ కార్డియాలజిస్ట్",
      "Neurology Specialist": "న్యూరాలజీ స్పెషలిస్ట్",
      "Pediatric Surgeon": "పీడియాట్రిక్ సర్జన్",
      "Orthopedic Expert": "ఆర్థోపెడిక్ నిపుణుడు",
      "General Physician": "జనరల్ ఫిజీషియన్",
      "Emergency Medicine Specialist": "ఎమర్జెన్సీ మెడిసిన్ స్పెషలిస్ట్"
    },
    chat: {
      welcome: "👋 నమస్కారం! నేను నోవాబోట్ (NovaBot). మీకు ఎలా సహాయం చేయగలను?",
      placeholder: "ఆరోగ్యం గురించి ఏదైనా అడగండి...",
      typing: "నోవాబోట్ టైప్ చేస్తోంది...",
      disclaimer: "⚠️ ఈ AI సహాయం కేవలం సమాచారం కోసం మాత్రమే.",
      error: "ఏదో పొరపాటు జరిగింది. మళ్ళీ ప్రయత్నించండి.",
      quickHelp: "త్వరిత సహాయం",
      send: "పంపండి"
    },
    symptoms: {
      fever: "జ్వరం",
      cough: "దగ్గు",
      headache: "తలనొప్పి",
      fatigue: "నీరసం",
      chest_pain: "ఛాతీ నొప్పి",
      breath: "శ్వాస తీసుకోవడంలో ఇబ్బంది",
      vomiting: "వాంతులు",
      dizziness: "కళ్ళు తిరగడం"
    }
  },
  TA: {
    navbar: {
      home: "முகப்பு",
      departments: "துறைகள்",
      doctors: "மருத்துவர்கள்",
      services: "சேவைகள்",
      contact: "தொடர்பு",
      book: "முன்பதிவு செய்யுங்கள்",
      tools: "சுகாதார கருவிகள்",
      queue: "நேரடி வரிசை",
    },
    hero: {
      tag: "சிறந்த மருத்துவ சிகிச்சை",
      title: "உங்கள் ஆரோக்கியமே எங்களின்",
      titleAccent: "முதல் முன்னுரிமை",
      desc: "எங்கள் நிபுணர் குழு மற்றும் நவீன வசதிகளுடன் உலகத்தரம் வாய்ந்த சுகாதார சேவையை அனுபவியுங்கள்.",
      cta: "முன்பதிவு செய்யுங்கள்",
      view: "சேவைகளைப் பார்க்கவும்",
    },
    common: {
      calculate: "கணக்கிடு",
      reset: "மீட்டமை",
      loading: "ஏற்றப்படுகிறது...",
      success: "வெற்றி!",
      results: "முடிவுகள்",
      error: "சர்வர் கிடைக்கவில்லை",
      booking: "முன்பதிவு செய்யப்படுகிறது...",
      selectLanguage: "மொழியைத் தேர்ந்தெடுக்கவும்",
      close: "மூடு"
    },
    bmi: {
      title: "பிஎம்ஐ கால்குலேட்டர்",
      weight: "எடை (கிலோ)",
      height: "உயரம் (செ.மீ)",
      category: "வகை",
      underweight: "குறைவான எடை",
      normal: "சாதாரண நிலை",
      overweight: "அதிக எடை",
      obese: "உடல் பருமன்",
    },
    footer: {
      rights: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
      quickLinks: "விரைவான இணைப்புகள்",
      contactUs: "எங்களைத் தொடர்பு கொள்ளுங்கள்",
    },
    phcLocator: {
      tag: "கிராமப்புற அணுகல்",
      title: "உங்கள் அருகிலுள்ள அரசு மையத்தைக் கண்டறியவும்",
      desc: "இலவச அல்லது சிறப்பு மருத்துவ சிகிச்சைக்காக உங்கள் அருகிலுள்ள அரசு ஆரம்ப சுகாதார நிலையங்கள் (PHC) மற்றும் சிவில் மருத்துவமனைகளைக் கண்டறிய நாங்கள் உதவுகிறோம்.",
      btn: "எனது இருப்பிடத்தைப் பெறுங்கள்",
      detecting: "இருப்பிடம் கண்டறியப்படுகிறது...",
      emptyTitle: "சுகாதார நிலையங்களைக் கண்டறியவும்",
      emptyDesc: "'எனது இருப்பிடத்தைப் பெறுங்கள்' என்பதைக் கிளிக் செய்து, அருகிலுள்ள அரசு சுகாதார நிலையங்களை வரைபடத்தில் பார்க்கவும்.",
      mapHeader: "ஊடாடும் வரைபடம்",
      showing: "அருகிலுள்ள மையங்களைக் காட்டுகிறது",
      youAreHere: "நீங்கள் இங்கே இருக்கிறீர்கள்",
      liveTracking: "நேரடி கண்காணிப்பு செயலில் உள்ளது",
      accuracy: "உயர் துல்லிய முறை",
      fallback: "இயல்பான இருப்பிடம் பயன்படுத்தப்படுகிறது",
      zeroCost: "இலவச வரைபடம்",
    },
    healthVault: {
      tag: "நகர்ப்புற ஸ்மார்ட் சுகாதாரம்",
      title: "உங்கள் டிஜிட்டல் ஹெல்த் வால்ட்",
      desc: "உங்கள் மருத்துவ அறிக்கைகள் மற்றும் ஆய்வக முடிவுகளை வங்கி தர குறியாக்கத்துடன் பாதுகாப்பாக சேமிக்கவும். தரவு பிரித்தெடுப்பதற்காக அனைத்து பதிவேற்றங்களும் தானாகவே செயல்படுத்தப்படுகின்றன.",
      uploadTitle: "கிளிக் செய்யவும் அல்லது அறிக்கைகளை இழுக்கவும்",
      uploadDesc: "PDF, JPG, PNG (அதிகபட்சம் 5MB) ஆதரிக்கிறது",
      uploading: "பாதுகாப்பாக பதிவேற்றப்படுகிறது...",
      searchPlaceholder: "பதிவுகளைத் தேடுங்கள்...",
      recentRecords: "சமீபத்திய பதிவுகள்",
      stored: "சேமிக்கப்பட்டது",
      syncing: "ஒத்திசைக்கப்படுகிறது",
      encrypted: "மறைக்குறியாக்கப்பட்டது",
      removed: "பதிவு நீக்கப்பட்டது",
      uploadSuccess: "கோப்பு வெற்றிகரமாக பதிவேற்றப்பட்டது!",
      uploadError: "பதிவேற்றம் தோல்வியடைந்தது. அமைப்புகளைச் சரிபார்க்கவும்.",
      diabetes_report: "நீரிழிவு நோயியல் அறிக்கை",
      hypertension_report: "உயர் இரத்த அழுத்தம் & இதய ஆபத்து",
      kidney_report: "நாள்பட்ட சிறுநீரக நோய் அறிக்கை",
      pathology: "நோயியல்",
      cardiology: "இதயவியல்",
      nephrology: "சிறுநீரகவியல்",
      urbanSmart: "நகர்ப்புற ஸ்மார்ட் சுகாதாரம்",
      certifiedVault: "மருத்துவமனை சான்றளிக்கப்பட்ட ஹெல்த் வால்ட்",
      vaultDesc: "உங்கள் சரிபார்க்கப்பட்ட மருத்துவ அறிக்கைகளை வங்கி தர குறியாக்கத்துடன் உலகளவில் அணுகவும். தரவு பிரித்தெடுப்பதற்காக அனைத்து பதிவேற்றங்களும் தானாகவே செயல்படுத்தப்படுகின்றன.",
      uploadLab: "ஆய்வக அறிக்கையை பதிவேற்றவும்",
      supportPdf: "PDF ஆதரிக்கிறது • அதிகபட்சம் 10MB",
      cloudSync: "கிளவுட் ஒத்திசைவு நிலை",
      smartVaultName: "MediNova ஸ்மார்ட்வால்ட்",
      activeBadge: "செயலில் உள்ளது",
      used: "பயன்படுத்தப்பட்டது",
      total: "மொத்தம்",
      searchRepo: "உங்கள் மருத்துவ களஞ்சியத்தைத் தேடுங்கள்...",
      reportsCount: "அறிக்கைகள்",
      verifiedReport: "சரிபார்க்கப்பட்ட அறிக்கை",
      certifiedBadge: "சான்றளிக்கப்பட்டது",
      viewReport: "மருத்துவ அறிக்கையைப் பார்க்கவும்",
      downloadPdf: "குறியாக்கம் செய்யப்பட்ட PDF ஐ பதிவிறக்கவும்",
      deletePerm: "நிரந்தரமாக நீக்கவும்",
      noRecords: "பதிவுகள் எதுவும் இல்லை",
      trySearch: "வேறு தேடல் வார்த்தை அல்லது வகையை முயற்சிக்கவும்.",
      modalDownload: "பதிவிறக்கம்",
      secureView: "பாதுகாப்பான பார்வை செயலில் உள்ளது",
      smartLink: "MediNova ஸ்மார்ட்லிங்க் தொழில்நுட்பம் • பல மண்டல குறியாக்கம்",
    },
    queue: {
      tag: "நேரடி மருத்துவமனை போக்குவரத்து",
      title: "நிகழ்நேர",
      titleAccent: "வரிசை நுண்ணறிவு",
      desc: "நீங்கள் வருவதற்கு முன் நேரடி OPD காத்திருப்பு நேரங்களையும் நோயாளி போக்குவரத்தையும் சரிபார்க்கவும். எங்கள் வரிசை முறை மூலம் உங்கள் ஆலோசனையை திறம்பட திட்டமிடுங்கள்.",
      notifyOn: "அறிவிப்புகள் ஆன்",
      notifyMe: "காத்திருப்பு மாற்றங்கள் குறித்து எனக்கு அறிவிக்கவும்",
      status: "துறை நிலை",
      live: "நேரடி",
      waiting: "காத்திருக்கும் நோயாளிகள்",
      avgWait: "சராசரி காத்திருப்பு நேரம்",
      serving: "தற்போது சேவை செய்யும் டோக்கன்",
      lastUpdated: "கடைசியாக புதுப்பிக்கப்பட்டது",
      justNow: "இப்போது",
      schedulePrompt: "அதற்கு பதிலாக ஒரு குறிப்பிட்ட நேரத்திற்கு திட்டமிட வேண்டுமா?",
      bookPrivate: "தனியார் ஸ்லாட்டை முன்பதிவு செய்யவும்",
    },
    healthTools: {
      tag: "சுகாதார துல்லியம்",
      title: "ஸ்மார்ட் சுகாதார கருவிகள்",
      desc: "எங்கள் AI-அடிப்படையிலான கால்குலேட்டர்கள் மூலம் உங்கள் சுகாதார அளவீடுகளை விரைவாக மதிப்பிடுங்கள்.",
      bmi: "பிஎம்ஐ கால்குலேட்டர்",
      weight: "எடை",
      height: "உயரம்",
      category: "வகை",
      underweight: "குறைவான எடை",
      normal: "சாதாரண நிலை",
      overweight: "அதிக எடை",
      obese: "உடல் பருமன்",
    },
    services: {
      tag: "மருத்துவமனை சேவைகள்",
      title: "சமச்சீர் சுகாதார பராமரிப்பு",
      desc: "மேம்பட்ட தொழில்நுட்பம் மற்றும் நிபுணத்துவ பராமரிப்புடன் உங்கள் தேவைகளுக்கு ஏற்ப உலகத்தரம் வாய்ந்த மருத்துவ சேவைகளை அனுபவிக்கவும்.",
      ai: { 
        title: "AI உதவியாளர்", 
        desc: "24/7 AI-இயக்கப்படும் சுகாதார வழிகாட்டுதல்.",
        details: "எங்கள் 24/7 AI-இயக்கப்படும் சுகாதார உதவியாளர் மருத்துவ கேள்விகளுக்கு உடனடி பதில்களை வழங்குகிறது, மேம்பட்ட வழிமுறைகளைப் பயன்படுத்தி அறிகுறிகளைத் வரிசைப்படுத்த உதவுகிறது.",
        features: ["அறிகுறி வரிசையாக்கம்", "உடனடி மருத்துவக் கேள்விகள்", "தனிப்பயனாக்கப்பட்ட சுகாதார உதவிக்குறிப்புகள்", "24/7 கிடைக்கும் தன்மை"]
      },
      doctors: { 
        title: "நிபுணர்கள்", 
        desc: "சிறந்த மருத்துவ நிபுணர்களுடன் இணையுங்கள்.",
        details: "இதயவியல், நரம்பியல் போன்ற பல்வேறு துறைகளில் உள்ள சிறந்த மருத்துவ நிபுணர்களின் நெட்வொர்க்கை அணுகுங்கள். உங்கள் சுகாதாரத் தேவைகளுக்கான நிபுணரை எளிதாகக் கண்டறியலாம்.",
        features: ["நிபுணர் ஆலோசனைகள்", "மல்டி-ஸ்பெஷாலிட்டி கேர்", "எளிதான இணைப்பு", "சரிபார்க்கப்பட்ட நிபுணர்கள்"]
      },
      checkup: { 
        title: "சுகாதார பரிசோதனைகள்", 
        desc: "முன்கூட்டியே கண்டறிய விரிவான பரிசோதனை.",
        details: "எங்கள் விரிவான ஸ்கீனிங் தொகுப்புகள் மூலம் சாத்தியமான சுகாதார பிரச்சினைகளை முன்கூட்டியே கண்டறியலாம். அனைத்து வயதினருக்கும் ஏற்றவாறு பரிசோதனைகள் வழங்கப்படுகின்றன.",
        features: ["முழு உடல் பரிசோதனை", "முன்கூட்டியே கண்டறிதல்", "தனிப்பயனாக்கப்பட்ட தொகுப்புகள்", "நிபுணர் பகுப்பாய்வு"]
      },
      mental: { 
        title: "மனநலம்", 
        desc: "தொழில்முறை ஆலோசனை மற்றும் ஆதரவு.",
        details: "எங்கள் தொழில்முறை ஆலோசனை சேவைகள் மூலம் உங்கள் மன நலத்திற்கு முன்னுரிமை அளிக்கவும். சிகிச்சை அமர்வுகளுக்கு பாதுகாப்பான மற்றும் ரகசியமான சூழலை நாங்கள் வழங்குகிறோம்.",
        features: ["ரகசிய ஆலோசனை", "மன அழுத்த மேலாண்மை", "சிகிச்சை அமர்வுகள்", "மன உணர்வு ஆதரவு"]
      },
      lab: { 
        title: "ஆய்வக சேவைகள்", 
        desc: "மேம்பட்ட கண்டறியும் சோதனை வசதிகள்.",
        details: "எங்கள் நவீன ஆய்வக வசதிகள் மூலம் துல்லியமான கண்டறிதலை அனுபவியுங்கள். பயனுள்ள சிகிச்சைத் திட்டமிடலுக்குத் தேவையான துல்லியமான தரவை விரைவாக வழங்குகிறோம்.",
        features: ["மேம்பட்ட கண்டறிதல்", "விரைவான முடிவுகள்", "பரந்த சோதனை வரம்பு", "சான்றளிக்கப்பட்ட ஆய்வகங்கள்"]
      },
      peds: { 
        title: "குழந்தை மருத்துவம்", 
        desc: "குழந்தைகளுக்கான சிறப்பு பராமரிப்பு.",
        details: "உங்கள் குழந்தைகளுக்கான சிறப்பு மற்றும் கனிவான பராமரிப்பு. எங்கள் குழந்தை மருத்துவத் துறை குழந்தைகளுக்கு ஏற்றவாறு வடிவமைக்கப்பட்டுள்ளது, தடுப்பூசிகள் முதல் சிகிச்சைகள் வரை வழங்குகிறோம்.",
        features: ["பச்சிளம் குழந்தை நிபுணர்", "குழந்தைகளுக்கு ஏற்ற சூழல்", "தடுப்பூசிகள்", "வளர்ச்சி கண்காணிப்பு"]
      },
      features: { 
        emergency: "அவசரநிலை", 
        monitoring: "நேரடி கண்காணிப்பு", 
        scheduling: "எளிதான முன்பதிவு" 
      },
      learnMore: "மேலும் அறிய",
      officialService: "அதிகாரப்பூர்வ மருத்துவமனை சேவை",
      getService: "இந்த சேவையைப் பெறுங்கள்"
    },
    appointment: {
      consultExperts: "நிபுணர்களுடன் கலந்தாலோசிக்கவும்",
      title: "உங்கள் மருத்துவ ஆலோசனையைத் திட்டமிடுங்கள்",
      desc: "சிறந்த ஆரோக்கியத்தை நோக்கி முதல் படியை எடுங்கள். படிவத்தை நிரப்பவும், உங்கள் சந்திப்பை உறுதிப்படுத்த எங்கள் குழு உங்களைத் தொடர்பு கொள்ளும்.",
      nameLabel: "முழு பெயர்",
      phoneLabel: "தொலைபேசி எண்",
      deptLabel: "துறை",
      docLabel: "மருத்துவர்",
      dateLabel: "தேதி",
      timeLabel: "நேரம்",
      msgLabel: "செய்தி (விருப்பத்திற்குரியது)",
      msgPlaceholder: "உங்கள் அறிகுறிகளைப் பற்றி எங்களிடம் கூறுங்கள்...",
      successDesc: "உங்கள் சந்திப்பு வெற்றிகரமாக பதிவு செய்யப்பட்டுள்ளது. எங்கள் குழு விரைவில் உங்களைத் தொடர்பு கொள்ளும்.",
      thanks: "மிக்க நன்றி!",
      confirmed: "உறுதிப்படுத்தப்பட்டது",
      status: "நிலை",
      nameReq: "முழு பெயர் தேவை",
      phoneReq: "தொலைபேசி எண் தேவை",
      phoneDigits: "தொலைபேசி எண் 10 இலக்கங்களாக இருக்க வேண்டும்",
      deptReq: "தயவுசெய்து ஒரு துறையைத் தேர்ந்தெடுக்கவும்",
      docReq: "தயவுசெய்து ஒரு மருத்துவரைத் தேர்ந்தெடுக்கவும்",
      dateReq: "தேதி தேவை",
      datePast: "தேதி கடந்த காலத்தில் இருக்க முடியாது",
      timeReq: "நேரம் தேவை",
      selectDept: "துறையைத் தேர்ந்தெடுக்கவும்",
      selectDoc: "மருத்துவரைத் தேர்ந்தெடுக்கவும்",
      selectDeptFirst: "முதலில் துறையைத் தேர்ந்தெடுக்கவும்"
    },
    doctors: {
      tag: "நிபுணர் குழு உறுப்பினர்கள்",
      title: "எங்கள் அர்ப்பணிப்புள்ள நிபுணர்களைச் சந்திக்கவும்",
      searchPlaceholder: "பெயர் அல்லது சிறப்பு மூலம் தேடுங்கள்...",
      bookNow: "இப்போதே பதிவு செய்யுங்கள்",
      noFound: "நிபுணர்கள் யாரும் தென்படவில்லை",
      noFoundDesc: "வேறு பெயர் அல்லது சிறப்புத் துறையைத் தேட முயற்சிக்கவும்.",
      clearSearch: "தேடலை நீக்குக",
      exp: "அனுபவம்",
      rating: "மதிப்பீடு"
    },
    departments: {
      tag: "மருத்துவ சிறப்பு",
      title: "சிறப்புத் துறைகள்",
      desc: "எங்கள் உலகத்தரம் வாய்ந்த நிபுணர்கள் பல்வேறு மருத்துவத் துறைகளில் நிபுணத்துவ பராமரிப்பை வழங்குகிறார்கள்.",
      cardiology: { name: "இதயவியல்", desc: "இதயம் மற்றும் வாஸ்குலர் பராமரிப்பு" },
      neurology: { name: "நரம்பியல்", desc: "மூளை மற்றும் நரம்பு பராமரிப்பு" },
      orthopedics: { name: "எலும்பியல்", desc: "எலும்பு மற்றும் கூட்டு பராமரிப்பு" },
      emergency: { name: "அவசர சிகிச்சை", desc: "24/7 தீவிர சிகிச்சை" },
      pediatrics: { name: "குழந்தை மருத்துவம்", desc: "குழந்தை ஆரோக்கியம்" },
      oncology: { name: "புற்றுநோயியல்", desc: "புற்றுநோய் சிகிச்சை" },
      "general-medicine": { name: "பொது மருத்துவம்", desc: "தடுப்பு பராமரிப்பு" }
    },
    specialties: {
      "Chief Cardiologist": "தலைமை இதய நோய் நிபுணர்",
      "Neurology Specialist": "நரம்பியல் நிபுணர்",
      "Pediatric Surgeon": "குழந்தை அறுவை சிகிச்சை நிபுணர்",
      "Orthopedic Expert": "எலும்பியல் நிபுணர்",
      "General Physician": "பொது மருத்துவர்",
      "Emergency Medicine Specialist": "அவசர சிகிச்சை நிபுணர்"
    },
    chat: {
      welcome: "👋 வணக்கம்! நான் மெடிபாட். நான் உங்களுக்கு எப்படி உதவ முடியும்?",
      placeholder: "ஏதாவது கேளுங்கள்...",
      typing: "மெடிபாட் டைப் செய்கிறது...",
      disclaimer: "⚠️ இந்த AI உதவியாளர் தகவல் நோக்கங்களுக்காக மட்டுமே.",
      error: "ஏதோ தவறு நடந்துவிட்டது. மீண்டும் முயற்சிக்கவும்.",
      quickHelp: "விரைவான உதவி",
      send: "அனுப்பு"
    },
    symptoms: {
      fever: "காய்ச்சல்",
      cough: "இருமல்",
      headache: "தலைவலி",
      fatigue: "சோர்வு",
      chest_pain: "நெஞ்சு வலி",
      breath: "மூச்சுத் திணறல்",
      vomiting: "வாந்தி",
      dizziness: "தலைச்சுற்றல்"
    }
  },
  MR: {
    navbar: {
      home: "मुख्यपृष्ठ",
      departments: "विभाग",
      doctors: "डॉक्टर",
      services: "सेवा",
      contact: "संपर्क",
      book: "अपॉइंटमेंट बुक करा",
      tools: "आरोग्य साधने",
      queue: "थेट रांग",
    },
    hero: {
      tag: "सर्वोत्तम वैद्यकीय सेवा",
      title: "तुमचे आरोग्य आमची",
      titleAccent: "पहिली पसंती",
      desc: "आमच्या तज्ज्ञ टीम आणि आधुनिक सुविधांसह जागतिक दर्जाच्या आरोग्यसेवेचा अनुभव घ्या.",
      cta: "अपॉइंटमेंट बुक करा",
      view: "सेवा पहा",
    },
    common: {
      calculate: "गणना करा",
      reset: "रीसेट करा",
      loading: "लोड होत आहे...",
      success: "यशस्वी!",
      results: "निकाल",
      error: "सर्व्हर उपलब्ध नाही",
      booking: "अपॉइंटमेंट बुक होत आहे...",
      selectLanguage: "भाषा निवडा",
      close: "बंद करा"
    },
    bmi: {
      title: "BMI कॅल्क्युलेटर",
      weight: "वजन (किलो)",
      height: "उंची (सेमी)",
      category: "श्रेणी",
      underweight: "कमी वजन",
      normal: "सामान्य",
      overweight: "जास्त वजन",
      obese: "लठ्ठपणा",
    },
    footer: {
      rights: "सर्व हक्क राखीव.",
      quickLinks: "द्रुत दुवे",
      contactUs: "आमच्याशी संपर्क साधा",
    },
    phcLocator: {
      tag: "ग्रामीण सुलभता",
      title: "तुमचे जवळचे सरकारी केंद्र शोधा",
      desc: "आम्ही तुम्हाला मोफत किंवा विशेष उपचारांसाठी तुमच्या परिसरातील सरकारी प्राथमिक आरोग्य केंद्रे (PHC) आणि नागरी रुग्णालये शोधण्यात मदत करतो.",
      btn: "माझे स्थान मिळवा",
      detecting: "स्थान शोधत आहे...",
      emptyTitle: "आरोग्य सेवा केंद्रे शोधा",
      emptyDesc: "तुमचे स्थान शोधण्यासाठी आणि नकाशावर जवळची सरकारी आरोग्य केंद्रे पाहण्यासाठी 'माझे स्थान मिळवा' वर क्लिक करा.",
      mapHeader: "परस्परसंवादी नकाशा",
      showing: "जवळपासची केंद्रे दाखवत आहे",
      youAreHere: "तुम्ही इथे आहात",
      liveTracking: "थेट ट्रॅकिंग सुरू आहे",
      accuracy: "उच्च अचूकता मोड",
      fallback: "डिफॉल्ट स्थान वापरले जात आहे",
      zeroCost: "मोफत नकाशा",
    },
    healthVault: {
      tag: "शहरी स्मार्ट आरोग्य सेवा",
      title: "तुमची डिजिटल हेल्थ वॉल्ट",
      desc: "तुमची वैद्यकीय प्रिस्क्रिप्शन आणि लॅब रिपोर्ट बँक-ग्रेड एन्क्रिप्शनसह सुरक्षितपणे साठवा. डेटा काढण्यासाठी सर्व अपलोड स्वयंचलितपणे प्रक्रिया केली जातात.",
      uploadTitle: "रिपोर्टवर क्लिक करा किंवा ड्रॅग करा",
      uploadDesc: "PDF, JPG, PNG (कमाल 5MB) ला समर्थन",
      uploading: "सुरक्षितपणे अपलोड होत आहे...",
      searchPlaceholder: "रेकॉर्ड शोधा...",
      recentRecords: "अलीकडील रेकॉर्ड",
      stored: "साठवले",
      syncing: "सिंक होत आहे",
      encrypted: "एन्क्रिप्टेड",
      removed: "रेकॉर्ड काढून टाकला",
      uploadSuccess: "फाईल यशस्वीरित्या अपलोड झाली!",
      uploadError: "अपलोड अयशस्वी. सेटिंग्ज तपासा.",
      diabetes_report: "मधुमेह पॅथॉलॉजी अहवाल",
      hypertension_report: "उच्च रक्तदाब आणि हृदय जोखीम",
      kidney_report: "क्रॉनिक किडनी रोग अहवाल",
      pathology: "पॅथॉलॉजी",
      cardiology: "कार्डिओलॉजी",
      nephrology: "नेफ्रोलॉजी",
      urbanSmart: "शहरी स्मार्ट आरोग्य सेवा",
      certifiedVault: "रुग्णालय प्रमाणित आरोग्य वॉल्ट",
      vaultDesc: "तुमच्या सत्यापित वैद्यकीय अहवालात बँक-ग्रेड एन्क्रिप्शनसह जागतिक स्तरावर प्रवेश करा. डेटा काढण्यासाठी सर्व अपलोड स्वयंचलितपणे प्रक्रिया केली जातात.",
      uploadLab: "प्रयोगशाळा अहवाल अपलोड करा",
      supportPdf: "PDF समर्थन • कमाल 10MB",
      cloudSync: "क्लाउड सिंक स्थिती",
      smartVaultName: "MediNova स्मार्टवॉल्ट",
      activeBadge: "सक्रिय",
      used: "वापरलेले",
      total: "एकूण",
      searchRepo: "तुमची वैद्यकीय भांडार शोधा...",
      reportsCount: "अहवाल",
      verifiedReport: "सत्यापित अहवाल",
      certifiedBadge: "प्रमाणित",
      viewReport: "वैद्यकीय अहवाल पहा",
      downloadPdf: "एन्क्रिप्टेड PDF डाउनलोड करा",
      deletePerm: "कायमस्वरूपी हटवा",
      noRecords: "कोणतेही रेकॉर्ड आढळले नाहीत",
      trySearch: "वेगळा कीवर्ड किंवा श्रेणी शोधण्याचा प्रयत्न करा.",
      modalDownload: "डाउनलोड",
      secureView: "सुरक्षित दृश्य सक्रिय",
      smartLink: "MediNova स्मार्टलिंक तंत्रज्ञान • बहु-प्रादेशिक एन्क्रिप्शन",
    },
    queue: {
      tag: "थेट रुग्णालय रहदारी",
      title: "रिअल-टाइम",
      titleAccent: "रांग इंटेलिजन्स",
      desc: "भेट देण्यापूर्वी थेट OPD प्रतीक्षा वेळ आणि रुग्णांच्या गर्दीची तपासणी करा. आमच्या रांग प्रणालीसह तुमच्या सल्ल्याचे कार्यक्षमतेने नियोजन करा.",
      notifyOn: "सूचना चालू",
      notifyMe: "प्रतीक्षा बदलांबद्दल मला सूचित करा",
      status: "विभाग स्थिती",
      live: "थेट",
      waiting: "प्रतीक्षारत रुग्ण",
      avgWait: "सरासरी प्रतीक्षा वेळ",
      serving: "आता टोकन सेवा देत आहे",
      lastUpdated: "शेवटचे अपडेट",
      justNow: "आत्ताच",
      schedulePrompt: "त्याऐवजी विशिष्ट वेळेसाठी शेड्यूल करू इच्छिता?",
      bookPrivate: "खाजगी स्लॉट बुक करा",
    },
    healthTools: {
      tag: "आरोग्य अचूकता",
      title: "स्मार्ट आरोग्य उपकरणे",
      desc: "आमच्या AI-सक्षम कॅल्क्युलेटरसह तुमच्या आरोग्य मेट्रिक्सचे त्वरित मूल्यांकन करा.",
      bmi: "बीएमआई कॅल्क्युलेटर",
      weight: "वजन",
      height: "उंची",
      category: "श्रेणी",
      underweight: "कमी वजन",
      normal: "सामान्य",
      overweight: "जास्त वजन",
      obese: "लठ्ठपणा",
    },
    services: {
      tag: "रुग्णालय सेवा",
      title: "सर्वसमावेशक आरोग्य सेवा",
      desc: "प्रगत तंत्रज्ञान आणि तज्ञ काळजीसह तुमच्या गरजांनुसार जागतिक दर्जाच्या वैद्यकीय सेवांचा अनुभव घ्या.",
      ai: { 
        title: "AI सहाय्यक", 
        desc: "24/7 AI-चालित आरोग्य मार्गदर्शन.",
        details: "आमचा 24/7 AI-चालित आरोग्य सहाय्यक वैद्यकीय प्रश्नांची त्वरित उत्तरे प्रदान करतो, प्रगत अल्गोरिदम वापरून लक्षणांचे वर्गीकरण करण्यास मदत करतो.",
        features: ["लक्षणे ट्राइएज", "त्वरीत वैद्यकीय प्रश्नोत्तरे", "वैयक्तिकृत आरोग्य टीप्स", "24/7 उपलब्धता"]
      },
      doctors: { 
        title: "तज्ञ", 
        desc: "उच्च-रेट केलेल्या वैद्यकीय व्यावसायिकांशी संपर्क साधा.",
        details: "हृदयरोगशास्त्र, न्यूरोलॉजी आणि ऑन्कोलॉजी यांसारख्या विविध क्षेत्रातील तज्ञ डॉक्टरांच्या नेटवर्कमध्ये प्रवेश करा.",
        features: ["तज्ञ सल्ला", "मल्टी-स्पेशालिटी केअर", "सुलभ कनेक्टिव्हिटी", "व्हेरिफाईड प्रोफेशनल"]
      },
      checkup: { 
        title: "आरोग्य तपासणी", 
        desc: "लवकर ओळखण्यासाठी सर्वसमावेशक स्क्रीनिंग.",
        details: "आमच्या सर्वसमावेशक स्क्रीनिंग पॅकेजसह संभाव्य आरोग्य समस्यांपासून दूर रहा. आम्ही लवकर ओळख आणि प्रतिबंध सुनिश्चित करण्यासाठी सर्व वयोगटांसाठी तपासणी ऑफर करतो.",
        features: ["फुल बॉडी स्क्रीनिंग", "लवकर शोधणे", "अनुकूलित पॅकेजेस", "तज्ञ विश्लेषण"]
      },
      mental: { 
        title: "मानसिक आरोग्य", 
        desc: "व्यावसायिक समुपदेशन आणि समर्थन.",
        details: "आमच्या व्यावसायिक समुपदेशन सेवांसह तुमच्या भावनिक कल्याणाला प्राधान्य द्या. आम्ही थेरपी सत्रांसाठी सुरक्षित, गोपनीय वातावरण प्रदान करतो.",
        features: ["गोपनीय समुपदेशन", "तणाव व्यवस्थापन", "थेरपी सत्र", "भावनिक आधार"]
      },
      lab: { 
        title: "लॅब सेवा", 
        desc: "प्रगत निदान चाचणी सुविधा.",
        details: "आमच्या अत्याधुनिक प्रयोगशाळा सुविधांसह अचूक निदानाचा अनुभव घ्या. आम्ही जलद परिणामांसह चाचण्यांची विस्तृत श्रेणी ऑफर करतो.",
        features: ["प्रगत निदान", "जलद निकाल", "विस्तृत चाचणी श्रेणी", "प्रमाणित प्रयोगशाळा"]
      },
      peds: { 
        title: "बालरोग", 
        desc: "शिशू आणि मुलांसाठी विशेष काळजी.",
        details: "तुमच्या लहान मुलांसाठी विशेष आणि प्रेमळ काळजी. आमचा बालरोग विभाग मुलांसाठी अनुकूल असा डिझाइन केला आहे, ज्यामध्ये लसीकरणापासून उपचारापर्यंत सर्व काही उपलब्ध आहे.",
        features: ["नवजात तज्ञ", "मुलांसाठी अनुकूल वातावरण", "लसीकरण", "वाढ देखरेख"]
      },
      features: { 
        emergency: "आणीबाणी", 
        monitoring: "लाइव्ह ट्रॅकिंग", 
        scheduling: "सोपे बुकिंग" 
      },
      learnMore: "अधिक जाणून घ्या",
      officialService: "अधिकृत रुग्णालय सेवा",
      getService: "ही सेवा मिळवा"
    },
    appointment: {
      consultExperts: "तज्ज्ञांचा सल्ला घ्या",
      title: "तुमचा वैद्यकीय सल्ला निर्धारित करा",
      desc: "उत्तम आरोग्याकडे पहिले पाऊल टाका. फॉर्म भरा आणि आमची टीम तुमची अपॉइंटमेंट निश्चित करण्यासाठी तुमच्याशी संपर्क साधेल.",
      nameLabel: "पूर्ण नाव",
      phoneLabel: "फोन नंबर",
      deptLabel: "विभाग",
      docLabel: "डॉक्टर",
      dateLabel: "तारीख",
      timeLabel: "वेळ",
      msgLabel: "संदेश (पर्यायी)",
      msgPlaceholder: "आम्हाला तुमच्या लक्षणांबद्दल सांगा...",
      successDesc: "तुमची अपॉइंटमेंट यशस्वीरित्या बुक झाली आहे. आमची टीम लवकरच तुमच्याशी संपर्क साधेल.",
      thanks: "खूप छान, धन्यवाद!",
      confirmed: "निश्चित",
      status: "स्थिती",
      nameReq: "पूर्ण नाव आवश्यक आहे",
      phoneReq: "फोन नंबर आवश्यक आहे",
      phoneDigits: "फोन नेमका 10 अंकी असावा",
      deptReq: "कृपया एक विभाग निवडा",
      docReq: "कृपया एक डॉक्टर निवडा",
      dateReq: "तारीख आवश्यक आहे",
      datePast: "तारीख भूतकाळातील नसावी",
      timeReq: "वेळ आवश्यक आहे",
      selectDept: "विभाग निवडा",
      selectDoc: "डॉक्टर निवडा",
      selectDeptFirst: "प्रथम विभाग निवडा"
    },
    doctors: {
      tag: "तज्ञ टीमचे सदस्य",
      title: "आमच्या समर्पित तज्ञांना भेटा",
      searchPlaceholder: "नाव किंवा स्पेशालिटीनुसार शोधा...",
      bookNow: "आत्ताच बुक करा",
      noFound: "कोणतेही तज्ञ आढळले नाहीत",
      noFoundDesc: "दुसऱ्या नावाचा किंवा स्पेशालिटीचा शोध घ्या.",
      clearSearch: "शोध साफ करा",
      exp: "अनुभव",
      rating: "रेटिंग"
    },
    departments: {
      tag: "वैद्यकीय उत्कृष्टता",
      title: "विशेषज्ञ विभाग",
      desc: "आमचे जागतिक दर्जाचे तज्ञ विविध वैद्यकीय क्षेत्रांमध्ये तज्ञ काळजी प्रदान करतात.",
      cardiology: { name: "हृदयरोग शास्त्र", desc: "हृदय आणि रक्तवाहिन्यांची काळजी" },
      neurology: { name: "न्यूरोलॉजी", desc: "मेंदू आणि मज्जातंतूची काळजी" },
      orthopedics: { name: "अस्थिरोग शास्त्र", desc: "हाडे आणि सांध्यांची काळजी" },
      emergency: { name: "आणीबाणी औषध", desc: "24/7 क्रिटिकल केअर" },
      pediatrics: { name: "बालरोग", desc: "बाल आरोग्य सेवा" },
      oncology: { name: "कर्करोग शास्त्र", desc: "कर्करोग उपचार" },
      "general-medicine": { name: "सामान्य औषध", desc: "प्रतिबंधात्मक काळजी" }
    },
    specialties: {
      "Chief Cardiologist": "मुख्य हृदयरोग तज्ञ",
      "Neurology Specialist": "न्यूरोलॉजी तज्ञ",
      "Pediatric Surgeon": "बालरोग शल्यचिकित्सक",
      "Orthopedic Expert": "अस्थिरोग तज्ञ",
      "General Physician": "सामान्य चिकित्सक",
      "Emergency Medicine Specialist": "आणीबाणी औषध तज्ञ"
    },
    chat: {
      welcome: "👋 नमस्कार! मी नोवाबॉट (NovaBot) आहे. मी तुम्हाला कशी मदत करू शकतो?",
      placeholder: "आरोग्याबद्दल काहीही विचारा...",
      typing: "नोवाबॉट टाईप करत आहे...",
      disclaimer: "⚠️ हा एआय सहाय्यक फक्त माहितीसाठी आहे.",
      error: "काहीतरी चूक झाली. कृपया पुन्हा प्रयत्न करा.",
      quickHelp: "त्वरित मदत",
      send: "पाठवा"
    },
    symptoms: {
      fever: "ताप",
      cough: "खोकला",
      headache: "डोकेदुखी",
      fatigue: "थकवा",
      chest_pain: "छातीत दुखणे",
      breath: "श्वास घेण्यास त्रास",
      vomiting: "उलट्या",
      dizziness: "चक्कर येणे"
    }
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("medinova_lang");
    return (saved === "HI" || saved === "EN" || saved === "TE" || saved === "TA" || saved === "MR") ? (saved as Language) : "EN";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("medinova_lang", lang);
  };

  const t = (path: string) => {
    const keys = path.split(".");
    let current: any = translations[language];
    for (const key of keys) {
      if (!current || current[key] === undefined) return path;
      current = current[key];
    }
    return current;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
